### ISSUE TITLE
How to set the proper routes for vue-router?

### ISSUE THREAD

**Issue by wushan** [PascalAnimateur/sails-hook-vue#1]
How can I use vue-router in this project when sails seems controlling the routes? Can I made all requests except the API to index.html ?

**Comment by PascalAnimateur** [comment]
You'll have to use a middleware like [express-history-api-fallback](https://www.npmjs.com/package/express-history-api-fallback).
See my answer here to get an idea of how to do this: http://stackoverflow.com/a/41604077/7146260
